[Server]
basePath = ""
host = "0.0.0.0"
port = 8989

[Speedtest]
downDataChunkSize = 4 #mb
downDataChunkCount = 4

[Log]
logFilePath = "/data/speedtest-ex/log/speedtest-ex.log"
maxLogSize = 5

[IPinfo]
ipinfo_api_key = ""
ipinfo_url = ""
model = "ipinfo"

[Database]
model = "bolt"
path = "/data/speedtest-ex/db/speedtest.db"

[Frontend]
chartlist = 100

[RevPing]
enable = true

[Auth]
enable = false
password = "password"
secret = "secret"
username = "admin"
